# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip:
    - uv-lock
    - cargo-fmt
exclude: |
  (?x)^(
    crates/fricon-ui/icons/.*|
    crates/fricon-ui/frontend/src/shared/lib/bindings\.ts|
    crates/fricon-ui/frontend/src/routeTree\.gen\.ts|
    crates/fricon/src/database/schema\.rs|
    Cargo\.lock|
    uv\.lock
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: fab64dc97d9fc7fdb2ff99d22c304bf681bc5b37  # frozen: v0.9.17
    hooks:
      - id: tombi-format
        args: ["--offline"]
  - repo: https://github.com/crate-ci/typos
    rev: 141bf8d1d11823cd5dc44d6b3c17d83b19015bcb  # frozen: v1
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: e99c5b43aa41681e83d439e6ebf3c82d7f3f6426  # frozen: 0.11.6
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b831c3dc5d27d9da294ae4e915773b99aa24a7c5  # frozen: v0.15.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: ec5ed61d83ae336c65c4c15396a23772ce9d2fcc  # frozen: 4.1.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix
  # Copied from maturin repo
  - repo: local
    hooks:
      - id: cargo-fmt # rustup component add rustfmt
        name: cargo fmt
        entry: cargo +nightly fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
