# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip:
    - uv-lock
    - cargo-fmt
exclude: |
  (?x)^(
    crates/fricon-ui/icons/.*|
    crates/fricon-ui/frontend/src/shared/lib/bindings\.ts|
    crates/fricon-ui/frontend/src/routeTree\.gen\.ts|
    crates/fricon/src/database/schema\.rs|
    Cargo\.lock|
    uv\.lock
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 5f88931d02e45a89a29c5624d6f0bf7ec46245e3  # frozen: v0.9.20
    hooks:
      - id: tombi-format
        args: ["--offline"]
  - repo: https://github.com/crate-ci/typos
    rev: cf5f1c29a8ac336af8568821ec41919923b05a83  # frozen: v1.45.1
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 6a280ba12b7901e47757c868c8c13c6a624c9ecb  # frozen: 0.11.7
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: d1b833175a5d08a925900115526febd8fe71c98e  # frozen: v0.15.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: ec5ed61d83ae336c65c4c15396a23772ce9d2fcc  # frozen: 4.1.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix
  # Copied from maturin repo
  - repo: local
    hooks:
      - id: cargo-fmt # rustup component add rustfmt
        name: cargo fmt
        entry: cargo +nightly fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
