# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip:
    - uv-lock
    - cargo-fmt
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/crate-ci/typos
    rev: 6cb49915af2e93e61f5f0d0a82216e28ad5c7c18  # frozen: v1
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 14ac15b122e538e407d036ff45e3895b7cf4a2bf  # frozen: 0.7.3
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 24e02b24b8ab2b7c76225602d13fa60e12d114e6  # frozen: v0.11.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 338ff784a3ead58a2c6e4e0f2e94e60ecb058ed6  # frozen: 3.4.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix
  # Copied from maturin repo
  - repo: local
    hooks:
      - id: cargo-fmt # rustup component add rustfmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
