packages:
  - crates/fricon-ui/frontend

catalogs:
  default:
    "@tsconfig/node-lts": ^24.0.0
    "@tsconfig/node-ts": ^23.6.4
    "@types/node": ^24.12.0
    typescript: ~6.0.2

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - msw
