// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getWorkspaceInfo: () => typedError<WorkspaceInfo, ApiError>(__TAURI_INVOKE("get_workspace_info")),
	listDatasets: (options: {
	search?: string | null,
	tags?: string[] | null,
	favoriteOnly?: boolean | null,
	statuses?: UiDatasetStatus[] | null,
	trashed?: boolean | null,
	sortBy?: UiDatasetSortBy | null,
	sortDir?: UiSortDirection | null,
	limit?: number | null,
	offset?: number | null,
} | null) => typedError<DatasetInfo[], ApiError>(__TAURI_INVOKE("list_datasets", { options })),
	listDatasetTags: () => typedError<string[], ApiError>(__TAURI_INVOKE("list_dataset_tags")),
	datasetDetail: (id: number) => typedError<DatasetDetail, ApiError>(__TAURI_INVOKE("dataset_detail", { id })),
	datasetChartData: (id: number, options: DatasetChartDataOptions) => typedError<ChartSnapshot, ApiError>(__TAURI_INVOKE("dataset_chart_data", { id, options })),
	getFilterTableData: (id: number, options: FilterTableOptions) => typedError<TableData, ApiError>(__TAURI_INVOKE("get_filter_table_data", { id, options })),
	datasetLiveChartData: (id: number, options: LiveChartDataOptions) => typedError<LiveChartDataResponse, ApiError>(__TAURI_INVOKE("dataset_live_chart_data", { id, options })),
	updateDatasetFavorite: (id: number, update: DatasetFavoriteUpdate) => typedError<null, ApiError>(__TAURI_INVOKE("update_dataset_favorite", { id, update })),
	updateDatasetInfo: (id: number, update: DatasetInfoUpdate) => typedError<null, ApiError>(__TAURI_INVOKE("update_dataset_info", { id, update })),
	getDatasetWriteStatus: (id: number) => typedError<DatasetWriteStatus, ApiError>(__TAURI_INVOKE("get_dataset_write_status", { id })),
	deleteDatasets: (ids: number[]) => typedError<DatasetDeleteResult[], ApiError>(__TAURI_INVOKE("delete_datasets", { ids })),
	trashDatasets: (ids: number[]) => typedError<DatasetDeleteResult[], ApiError>(__TAURI_INVOKE("trash_datasets", { ids })),
	restoreDatasets: (ids: number[]) => typedError<DatasetDeleteResult[], ApiError>(__TAURI_INVOKE("restore_datasets", { ids })),
	emptyTrash: () => typedError<DatasetDeleteResult[], ApiError>(__TAURI_INVOKE("empty_trash")),
	batchUpdateDatasetTags: (update: BatchTagUpdateOptions) => typedError<DatasetTagBatchResult[], ApiError>(__TAURI_INVOKE("batch_update_dataset_tags", { update })),
	deleteTag: (tag: string) => typedError<null, ApiError>(__TAURI_INVOKE("delete_tag", { tag })),
	renameTag: (oldName: string, newName: string) => typedError<null, ApiError>(__TAURI_INVOKE("rename_tag", { oldName, newName })),
	mergeTag: (source: string, target: string) => typedError<null, ApiError>(__TAURI_INVOKE("merge_tag", { source, target })),
	exportDatasetsDialog: (ids: number[]) => typedError<string[] | null, ApiError>(__TAURI_INVOKE("export_datasets_dialog", { ids })),
	previewImportDialog: () => typedError<UiPreviewImportResult[] | null, ApiError>(__TAURI_INVOKE("preview_import_dialog")),
	previewImportFiles: (paths: string[]) => typedError<UiPreviewImportResult[], ApiError>(__TAURI_INVOKE("preview_import_files", { paths })),
	importDataset: (archivePath: string, force: boolean) => typedError<DatasetInfo, ApiError>(__TAURI_INVOKE("import_dataset", { archivePath, force })),
};

/** Events */
export const events = {
	datasetChanged: makeEvent<DatasetChanged>("dataset-changed"),
};

/* Types */
export type ApiError = {
	code: ApiErrorCode,
	message: string,
};

export type ApiErrorCode = "dataset_not_found" | "dataset_deleted" | "dataset_not_trashed" | "archive_version_unsupported" | "invalid_tag" | "same_tag_name" | "same_source_target" | "workspace" | "charts" | "dialog" | "validation" | "internal";

export type BatchTagUpdateOptions = {
	ids: number[],
	add?: string[] | null,
	remove?: string[] | null,
};

export type ChartCommonOptions = {
	start: number | null,
	end: number | null,
	indexFilters: number[] | null,
	excludeColumns: string[] | null,
};

export type ChartSnapshot = { type: "line" } & (LineChartSnapshot) | { type: "heatmap" } & (HeatmapChartSnapshot) | { type: "scatter" } & (ScatterChartSnapshot);

export type ColumnInfo = {
	name: string,
	isComplex: boolean,
	isTrace: boolean,
	isIndex: boolean,
};

export type ColumnUniqueValue = {
	index: number,
	displayValue: string,
};

export type ComplexViewOption = "real" | "imag" | "mag" | "arg";

/**
 *  Payload for the `dataset-changed` Tauri event.
 * 
 *  Serialised as an internally-tagged JSON object (discriminant field: `kind`).
 *  Variants that concern a specific dataset carry an `info` field; the
 *  `globalTagsChanged` variant has no `info`.
 */
export type DatasetChanged = 
// New dataset was created by ingest (Writing status).
{ kind: "created"; info: DatasetInfo } | 
// Write session transitioned the dataset to Completed or Aborted.
{ kind: "statusChanged"; info: DatasetInfo } | 
// Name, description, or favorite flag changed.
{ kind: "metadataUpdated"; info: DatasetInfo } | 
// Tags were added or removed on a specific dataset.
{ kind: "tagsChanged"; info: DatasetInfo } | 
// Dataset was moved to trash.
{ kind: "trashed"; info: DatasetInfo } | 
// Dataset was restored from trash.
{ kind: "restored"; info: DatasetInfo } | 
// Dataset was permanently deleted.
{ kind: "deleted"; info: DatasetInfo } | 
// An existing dataset was replaced by a force-import.
{ kind: "imported"; info: DatasetInfo } | 
// A global tag was deleted, renamed, or merged across all datasets.
{ kind: "globalTagsChanged" };

export type DatasetChartDataOptions = { chartType: "line" } & (LineChartDataOptions) | { chartType: "heatmap" } & (HeatmapChartDataOptions) | { chartType: "scatter" } & (ScatterChartDataOptions);

export type DatasetDeleteResult = {
	id: number,
	success: boolean,
	error: DatasetOperationError | null,
};

export type DatasetDetail = {
	id: number,
	name: string,
	description: string,
	favorite: boolean,
	tags: string[],
	status: UiDatasetStatus,
	createdAt: string,
	trashedAt: string | null,
	deletedAt: string | null,
	payloadAvailable: boolean,
	columns: ColumnInfo[],
};

export type DatasetFavoriteUpdate = {
	favorite: boolean,
};

export type DatasetInfo = {
	id: number,
	name: string,
	description: string,
	favorite: boolean,
	tags: string[],
	status: UiDatasetStatus,
	createdAt: string,
	trashedAt: string | null,
	deletedAt: string | null,
};

export type DatasetInfoUpdate = {
	name?: string | null,
	description?: string | null,
	favorite?: boolean | null,
	tags?: string[] | null,
};

export type DatasetListOptions = {
	search?: string | null,
	tags?: string[] | null,
	favoriteOnly?: boolean | null,
	statuses?: UiDatasetStatus[] | null,
	trashed?: boolean | null,
	sortBy?: UiDatasetSortBy | null,
	sortDir?: UiSortDirection | null,
	limit?: number | null,
	offset?: number | null,
};

export type DatasetOperationError = {
	code: ApiErrorCode,
	message: string,
};

export type DatasetTagBatchResult = {
	id: number,
	success: boolean,
	addError: DatasetOperationError | null,
	removeError: DatasetOperationError | null,
};

export type DatasetWriteStatus = {
	rowCount: number,
};

export type FilterTableOptions = {
	excludeColumns?: string[] | null,
};

export type FlatSeries = { shape: "xy" } & (FlatXYSeries) | { shape: "xyz" } & (FlatXYZSeries);

export type FlatXYSeries = {
	id: string,
	label: string,
	values: number[],
	pointCount: number,
};

export type FlatXYZSeries = {
	id: string,
	label: string,
	values: number[],
	pointCount: number,
};

export type HeatmapChartDataOptions = {
	series: string,
	xColumn: string | null,
	yColumn: string,
	complexViewSingle: ComplexViewOption | null,
} & (ChartCommonOptions);

export type HeatmapChartSnapshot = {
	xName: string,
	yName: string,
	xCategories: number[],
	yCategories: number[],
	series: FlatXYZSeries[],
};

export type LineChartDataOptions = {
	series: string,
	xColumn: string | null,
	complexViews: ComplexViewOption[] | null,
} & (ChartCommonOptions);

export type LineChartSnapshot = {
	xName: string,
	series: FlatXYSeries[],
};

export type LiveChartAppendOperation = { kind: "append_points"; series_id: string; values: number[]; point_count: number } | { kind: "append_series"; series: FlatSeries } | { kind: "append_heatmap_categories"; x_categories: number[] | null; y_categories: number[] | null };

export type LiveChartDataOptions = { chartType: "line" } & (LiveLineOptions) | { chartType: "heatmap" } & (LiveHeatmapOptions) | { chartType: "scatter" } & (LiveScatterOptions);

export type LiveChartDataResponse = { mode: "reset"; row_count: number; snapshot: ChartSnapshot } | { mode: "append"; row_count: number; ops: LiveChartAppendOperation[] };

export type LiveHeatmapOptions = {
	series: string,
	complexViewSingle: ComplexViewOption | null,
	knownRowCount?: number | null,
};

export type LiveLineOptions = {
	series: string,
	complexViews: ComplexViewOption[] | null,
	tailCount: number,
	knownRowCount?: number | null,
};

export type LiveScatterOptions = {
	scatter: ScatterModeOptions,
	tailCount: number,
	knownRowCount?: number | null,
};

export type Row = {
	displayValues: string[],
	valueIndices: number[],
	index: number,
};

export type ScatterChartDataOptions = {
	scatter: ScatterModeOptions,
} & (ChartCommonOptions);

export type ScatterChartSnapshot = {
	xName: string,
	yName: string,
	series: FlatXYSeries[],
};

export type ScatterModeOptions = { mode: "complex"; series: string } | { mode: "trace_xy"; traceXColumn: string; traceYColumn: string } | { mode: "xy"; xColumn: string; yColumn: string };

export type TableData = {
	fields: string[],
	rows: Row[],
	columnUniqueValues: { [key in string]: ColumnUniqueValue[] },
};

export type UiDatasetSortBy = "id" | "name" | "createdAt";

export type UiDatasetStatus = "Writing" | "Completed" | "Aborted";

export type UiExportedMetadata = {
	uid: string,
	name: string,
	description: string,
	favorite: boolean,
	status: UiDatasetStatus,
	createdAt: string,
	tags: string[],
};

export type UiFieldDiff = {
	field: string,
	existingValue: string,
	incomingValue: string,
};

export type UiImportConflict = {
	existing: UiExportedMetadata,
	diffs: UiFieldDiff[],
};

export type UiImportPreview = {
	metadata: UiExportedMetadata,
	conflict: UiImportConflict | null,
};

export type UiPreviewImportResult = {
	archivePath: string,
	preview: UiImportPreview,
};

export type UiSortDirection = "asc" | "desc";

export type WorkspaceInfo = {
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

