// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getWorkspaceInfo() : Promise<Result<WorkspaceInfo, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workspace_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDatasets(options: DatasetListOptions | null) : Promise<Result<DatasetInfo[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_datasets", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDatasetTags() : Promise<Result<string[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dataset_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async datasetDetail(id: number) : Promise<Result<DatasetDetail, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dataset_detail", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async datasetChartData(id: number, options: DatasetChartDataOptions) : Promise<Result<DataResponse, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dataset_chart_data", { id, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFilterTableData(id: number, options: FilterTableOptions) : Promise<Result<TableData, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_filter_table_data", { id, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDatasetFavorite(id: number, update: DatasetFavoriteUpdate) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dataset_favorite", { id, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDatasetInfo(id: number, update: DatasetInfoUpdate) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dataset_info", { id, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDatasetWriteStatus(id: number) : Promise<Result<DatasetWriteStatus, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dataset_write_status", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
datasetCreated: DatasetCreated,
datasetUpdated: DatasetUpdated
}>({
datasetCreated: "dataset-created",
datasetUpdated: "dataset-updated"
})

/** user-defined constants **/



/** user-defined types **/

export type ColumnInfo = { name: string; isComplex: boolean; isTrace: boolean; isIndex: boolean }
export type ColumnUniqueValue = { index: number; displayValue: string }
export type ComplexViewOption = "real" | "imag" | "mag" | "arg"
export type DataResponse = { type: Type; xName: string; yName: string | null; xCategories: number[] | null; yCategories: number[] | null; series: Series[] }
export type DatasetChartDataOptions = ({ chartType: "line" } & LineChartDataOptions) | ({ chartType: "heatmap" } & HeatmapChartDataOptions) | ({ chartType: "scatter" } & ScatterChartDataOptions)
export type DatasetCreated = DatasetInfo
export type DatasetDetail = { id: number; name: string; description: string; favorite: boolean; tags: string[]; status: UiDatasetStatus; createdAt: string; columns: ColumnInfo[] }
export type DatasetFavoriteUpdate = { favorite: boolean }
export type DatasetInfo = { id: number; name: string; description: string; favorite: boolean; tags: string[]; status: UiDatasetStatus; createdAt: string }
export type DatasetInfoUpdate = { name?: string | null; description?: string | null; favorite?: boolean | null; tags?: string[] | null }
export type DatasetListOptions = { search?: string | null; tags?: string[] | null; favoriteOnly?: boolean | null; statuses?: UiDatasetStatus[] | null; sortBy?: UiDatasetSortBy | null; sortDir?: UiSortDirection | null; limit?: number | null; offset?: number | null }
export type DatasetUpdated = DatasetInfo
export type DatasetWriteStatus = { rowCount: number; isComplete: boolean }
export type Error = { message: string }
export type FilterTableOptions = { excludeColumns?: string[] | null }
export type HeatmapChartDataOptions = ({ start: number | null; end: number | null; indexFilters: number[] | null; excludeColumns: string[] | null }) & { series: string; xColumn: string | null; yColumn: string; complexViewSingle: ComplexViewOption | null }
export type LineChartDataOptions = ({ start: number | null; end: number | null; indexFilters: number[] | null; excludeColumns: string[] | null }) & { series: string; xColumn: string | null; complexViews: ComplexViewOption[] | null }
export type Row = { displayValues: string[]; valueIndices: number[]; index: number }
export type ScatterChartDataOptions = ({ start: number | null; end: number | null; indexFilters: number[] | null; excludeColumns: string[] | null }) & { scatter: ScatterModeOptions }
export type ScatterModeOptions = { mode: "complex"; series: string } | { mode: "trace_xy"; traceXColumn: string; traceYColumn: string } | { mode: "xy"; xColumn: string; yColumn: string; binColumn: string | null }
export type Series = { name: string; data: number[][] }
export type TableData = { fields: string[]; rows: Row[]; columnUniqueValues: Partial<{ [key in string]: ColumnUniqueValue[] }> }
export type Type = "line" | "heatmap" | "scatter"
export type UiDatasetSortBy = "id" | "name" | "createdAt"
export type UiDatasetStatus = "Writing" | "Completed" | "Aborted"
export type UiSortDirection = "asc" | "desc"
export type WorkspaceInfo = { path: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
