[lint]
select = ["ALL"]
ignore = [
    # Conflict with formatter
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "COM812", # missing-trailing-comma
    # Not applicable
    "PLC0414", # useless-import-alias
]
[lint.pydocstyle]
convention = "google"
[lint.isort]
known-first-party = ["fricon"]
required-imports = ["from __future__ import annotations"]
