[package]
name = "fricon-py"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true

[lib]
doctest = false

[dependencies]
fricon = { path = "../fricon" }
fricon-ui = { path = "../fricon-ui" }

anyhow = { workspace = true }
arrow = { workspace = true, features = ["pyarrow"] }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
itertools = { workspace = true }
ndarray = { workspace = true }
num = { workspace = true }
numpy = { workspace = true }
pyo3 = { workspace = true, features = [
    "anyhow",
    "chrono",
    "num-complex",
    "abi3-py39",
    "generate-import-lib",
] }
pyo3-async-runtimes = { workspace = true, features = ["tokio-runtime"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
