from datetime import datetime
from typing import type_check_only

import pyarrow as pa

__all__ = ["connect", "lib_main"]

async def connect(addr: str) -> Client: ...
def lib_main() -> int: ...
@type_check_only
class Client:
    async def create_dataset(
        self, name: str, description: str | None = ..., tags: list[str] | None = ...
    ) -> DatasetWriter: ...
    async def get_dataset(self, uid: str) -> DatasetInfo: ...

@type_check_only
class DatasetWriter:
    def write(self, data: pa.RecordBatch) -> None: ...
    async def aclose(self) -> None: ...
    @property
    def uid(self) -> str: ...

@type_check_only
class DatasetInfo:
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str | None: ...
    @property
    def tags(self) -> list[str]: ...
    @property
    def path(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...
