name: Deploy Docs

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - "**"

concurrency:
  group: deploy-docs
  cancel-in-progress: false

jobs:
  mike-deploy:
    name: Mike Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libxdo-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - name: Rust cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Install build dependencies
        uses: taiki-e/install-action@a1df9120380005ebdc788c62449b841b205541dd # v2
        with:
          tool: protoc
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.x"
          cache: "pnpm"
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch origin gh-pages --depth=1
      - name: Set docs version tag
        run: uv run scripts/set-docs-version.py
      - name: Build docs
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: uv run --group docs mike deploy --push dev
      - name: Build docs
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: uv run --group docs mike deploy --push --update-aliases "$FRICON_DOCS_TAG" latest
